### ISSUE TITLE
[Component] RGBA colours outside range crash

### ISSUE THREAD

**Issue by russellbanks** [kirill-grouchnikov/aurora#34]
This is a crash that occurs quite inconsistently but will occur during normal usage. It will usually occur for me after a few minutes of usage of my app, but I can reproduce it quickly by just switching between tabs over and over again. I expect that this same bug is existent in other components as I have had this occur before I even used Tabs (I couldn't reproduce it consistently), although less frequently.

https://user-images.githubusercontent.com/74878137/169145310-f90a06b9-6bd7-4356-a8bf-fec428d419f1.mp4

I have attached the stacktrace below but the parts that point to Aurora are [AuroraTabs.kt:378](https://github.com/kirill-grouchnikov/aurora/blob/639780577fcc60d7b2a14f514c88d7d892990042/component/src/desktopMain/kotlin/org/pushingpixels/aurora/component/AuroraTabButton.kt#L378) and [AuroraTabs.kt:328](https://github.com/kirill-grouchnikov/aurora/blob/639780577fcc60d7b2a14f514c88d7d892990042/component/src/desktopMain/kotlin/org/pushingpixels/aurora/component/AuroraTabButton.kt#L328). I expect this could be due to float conversion as it is stating `1.0000001` > `1`.

```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: red = 0.0, green = 0.0, blue = 0.0, alpha = 1.0000001 outside the range for sRGB IEC61966-2.1 (id=0, model=Rgb)
	at androidx.compose.ui.graphics.ColorKt.Color(Color.kt:402)
	at androidx.compose.ui.graphics.Color.copy-wmQWz5c(Color.kt:261)
	at androidx.compose.ui.graphics.Color.copy-wmQWz5c$default(Color.kt:256)
	at androidx.compose.ui.graphics.SkiaBackedPaint.setAlpha(SkiaBackedPaint.skiko.kt:40)
	at androidx.compose.ui.graphics.ShaderBrush.applyTo-Pq9zytI(Brush.kt:653)
	at androidx.compose.ui.graphics.drawscope.CanvasDrawScope.configurePaint-swdJneE(CanvasDrawScope.kt:633)
	at androidx.compose.ui.graphics.drawscope.CanvasDrawScope.configurePaint-swdJneE$default(CanvasDrawScope.kt:623)
	at androidx.compose.ui.graphics.drawscope.CanvasDrawScope.drawPath-GBMwjPU(CanvasDrawScope.kt:475)
	at androidx.compose.ui.node.LayoutNodeDrawScope.drawPath-GBMwjPU(LayoutNodeDrawScope.kt)
	at androidx.compose.ui.graphics.OutlineKt.drawOutline-hn5TExg(Outline.kt:213)
	at androidx.compose.ui.graphics.OutlineKt.drawOutline-hn5TExg$default(Outline.kt:187)
	at org.pushingpixels.aurora.theming.painter.fill.FractionBasedFillPainter.paintContourBackground-eZhPAX0(FractionBasedFillPainter.kt:46)
	at org.pushingpixels.aurora.component.AuroraTabButtonKt$AuroraTabButton$2$2$1.invoke(AuroraTabButton.kt:378)
	at org.pushingpixels.aurora.component.AuroraTabButtonKt$AuroraTabButton$2$2$1.invoke(AuroraTabButton.kt:328)
	at androidx.compose.ui.draw.DrawBackgroundModifier.draw(DrawModifier.kt:101)
	at androidx.compose.ui.node.DrawEntity.draw(DrawEntity.kt:98)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:322)
	at androidx.compose.ui.node.LayoutNodeWrapper.access$drawContainedDrawModifiers(LayoutNodeWrapper.kt:60)
	at androidx.compose.ui.node.LayoutNodeWrapper$invoke$1.invoke(LayoutNodeWrapper.kt:342)
	at androidx.compose.ui.node.LayoutNodeWrapper$invoke$1.invoke(LayoutNodeWrapper.kt:341)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2064)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:115)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui(OwnerSnapshotObserver.kt:78)
	at androidx.compose.ui.node.LayoutNodeWrapper.invoke(LayoutNodeWrapper.kt:341)
	at androidx.compose.ui.node.LayoutNodeWrapper$invokeOnCanvasInstance$1.invoke(LayoutNodeWrapper.kt:163)
	at androidx.compose.ui.node.LayoutNodeWrapper$invokeOnCanvasInstance$1.invoke(LayoutNodeWrapper.kt:163)
	at androidx.compose.ui.platform.SkiaLayer.performDrawLayer(SkiaLayer.skiko.kt:264)
	at androidx.compose.ui.platform.SkiaLayer.drawLayer(SkiaLayer.skiko.kt:225)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:307)
	at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:139)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:320)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:312)
	at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:810)
	at androidx.compose.ui.node.InnerPlaceable.performDraw(InnerPlaceable.kt:90)
	at androidx.compose.ui.node.LayoutNodeDrawScope.drawContent(LayoutNodeDrawScope.kt:48)
	at androidx.compose.foundation.NoIndication$NoIndicationInstance.drawIndication(Indication.kt:136)
	at androidx.compose.foundation.IndicationModifier.draw(Indication.kt:183)
	at androidx.compose.ui.node.DrawEntity.draw(DrawEntity.kt:98)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:322)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:312)
	at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:810)
	at androidx.compose.ui.node.InnerPlaceable.performDraw(InnerPlaceable.kt:90)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:320)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:312)
	at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:810)
	at androidx.compose.ui.node.InnerPlaceable.performDraw(InnerPlaceable.kt:90)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:320)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:312)
	at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:139)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:320)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:312)
	at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:810)
	at androidx.compose.ui.node.InnerPlaceable.performDraw(InnerPlaceable.kt:90)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:320)
	at androidx.compose.ui.node.LayoutNodeWrapper.access$drawContainedDrawModifiers(LayoutNodeWrapper.kt:60)
	at androidx.compose.ui.node.LayoutNodeWrapper$invoke$1.invoke(LayoutNodeWrapper.kt:342)
	at androidx.compose.ui.node.LayoutNodeWrapper$invoke$1.invoke(LayoutNodeWrapper.kt:341)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2064)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:115)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui(OwnerSnapshotObserver.kt:78)
	at androidx.compose.ui.node.LayoutNodeWrapper.invoke(LayoutNodeWrapper.kt:341)
	at androidx.compose.ui.node.LayoutNodeWrapper$invokeOnCanvasInstance$1.invoke(LayoutNodeWrapper.kt:163)
	at androidx.compose.ui.node.LayoutNodeWrapper$invokeOnCanvasInstance$1.invoke(LayoutNodeWrapper.kt:163)
	at androidx.compose.ui.platform.SkiaLayer.performDrawLayer(SkiaLayer.skiko.kt:264)
	at androidx.compose.ui.platform.SkiaLayer.drawLayer(SkiaLayer.skiko.kt:225)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:307)
	at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:139)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:320)
	at androidx.compose.ui.node.LayoutNodeWrapper.access$drawContainedDrawModifiers(LayoutNodeWrapper.kt:60)
	at androidx.compose.ui.node.LayoutNodeWrapper$invoke$1.invoke(LayoutNodeWrapper.kt:342)
	at androidx.compose.ui.node.LayoutNodeWrapper$invoke$1.invoke(LayoutNodeWrapper.kt:341)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2064)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:115)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui(OwnerSnapshotObserver.kt:78)
	at androidx.compose.ui.node.LayoutNodeWrapper.invoke(LayoutNodeWrapper.kt:341)
	at androidx.compose.ui.node.LayoutNodeWrapper$invokeOnCanvasInstance$1.invoke(LayoutNodeWrapper.kt:163)
	at androidx.compose.ui.node.LayoutNodeWrapper$invokeOnCanvasInstance$1.invoke(LayoutNodeWrapper.kt:163)
	at androidx.compose.ui.platform.SkiaLayer.performDrawLayer(SkiaLayer.skiko.kt:264)
	at androidx.compose.ui.platform.SkiaLayer.drawLayer(SkiaLayer.skiko.kt:225)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:307)
	at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:139)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:320)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:312)
	at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:810)
	at androidx.compose.ui.node.InnerPlaceable.performDraw(InnerPlaceable.kt:90)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:320)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:312)
	at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:139)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:320)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:312)
	at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:139)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:320)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:312)
	at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:810)
	at androidx.compose.ui.node.InnerPlaceable.performDraw(InnerPlaceable.kt:90)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:320)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:312)
	at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:810)
	at androidx.compose.ui.node.InnerPlaceable.performDraw(InnerPlaceable.kt:90)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:320)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:312)
	at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:139)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:320)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:312)
	at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:810)
	at androidx.compose.ui.node.InnerPlaceable.performDraw(InnerPlaceable.kt:90)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:320)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:312)
	at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:810)
	at androidx.compose.ui.node.InnerPlaceable.performDraw(InnerPlaceable.kt:90)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:320)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:312)
	at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:810)
	at androidx.compose.ui.node.InnerPlaceable.performDraw(InnerPlaceable.kt:90)
	at androidx.compose.ui.node.LayoutNodeDrawScope.drawContent(LayoutNodeDrawScope.kt:48)
	at org.pushingpixels.aurora.theming.AuroraBackground.draw(AuroraBackground.kt:102)
	at androidx.compose.ui.node.DrawEntity.draw(DrawEntity.kt:98)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:322)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:312)
	at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:139)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:320)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:312)
	at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:810)
	at androidx.compose.ui.node.InnerPlaceable.performDraw(InnerPlaceable.kt:90)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:320)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:312)
	at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:139)
	at androidx.compose.ui.node.LayoutNodeDrawScope.drawContent(LayoutNodeDrawScope.kt:48)
	at androidx.compose.ui.draw.DrawBackgroundModifier.draw(DrawModifier.kt:102)
	at androidx.compose.ui.node.DrawEntity.draw(DrawEntity.kt:98)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:322)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:312)
	at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:139)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:320)
	at androidx.compose.ui.node.LayoutNodeWrapper.access$drawContainedDrawModifiers(LayoutNodeWrapper.kt:60)
	at androidx.compose.ui.node.LayoutNodeWrapper$invoke$1.invoke(LayoutNodeWrapper.kt:342)
	at androidx.compose.ui.node.LayoutNodeWrapper$invoke$1.invoke(LayoutNodeWrapper.kt:341)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2064)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:115)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui(OwnerSnapshotObserver.kt:78)
	at androidx.compose.ui.node.LayoutNodeWrapper.invoke(LayoutNodeWrapper.kt:341)
	at androidx.compose.ui.node.LayoutNodeWrapper$invokeOnCanvasInstance$1.invoke(LayoutNodeWrapper.kt:163)
	at androidx.compose.ui.node.LayoutNodeWrapper$invokeOnCanvasInstance$1.invoke(LayoutNodeWrapper.kt:163)
	at androidx.compose.ui.platform.SkiaLayer.performDrawLayer(SkiaLayer.skiko.kt:264)
	at androidx.compose.ui.platform.SkiaLayer.drawLayer(SkiaLayer.skiko.kt:225)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:307)
	at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:810)
	at androidx.compose.ui.node.InnerPlaceable.performDraw(InnerPlaceable.kt:90)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:320)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:312)
	at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:810)
	at androidx.compose.ui.platform.SkiaBasedOwner.draw(SkiaBasedOwner.skiko.kt:334)
	at androidx.compose.ui.ComposeScene.render(ComposeScene.skiko.kt:386)
	at androidx.compose.ui.awt.ComposeLayer$1$onRender$1.invoke(ComposeLayer.desktop.kt:236)
	at androidx.compose.ui.awt.ComposeLayer$1$onRender$1.invoke(ComposeLayer.desktop.kt:235)
	at androidx.compose.ui.awt.ComposeLayer.catchExceptions(ComposeLayer.desktop.kt:88)
	at androidx.compose.ui.awt.ComposeLayer.access$catchExceptions(ComposeLayer.desktop.kt:68)
	at androidx.compose.ui.awt.ComposeLayer$1.onRender(ComposeLayer.desktop.kt:235)
	at org.jetbrains.skiko.SkiaLayer.update$skiko(SkiaLayer.awt.kt:455)
	at org.jetbrains.skiko.redrawer.Direct3DRedrawer.update(Direct3DRedrawer.kt:54)
	at org.jetbrains.skiko.redrawer.Direct3DRedrawer.access$update(Direct3DRedrawer.kt:10)
	at org.jetbrains.skiko.redrawer.Direct3DRedrawer$frameDispatcher$1.invokeSuspend(Direct3DRedrawer.kt:28)
	at org.jetbrains.skiko.redrawer.Direct3DRedrawer$frameDispatcher$1.invoke(Direct3DRedrawer.kt)
	at org.jetbrains.skiko.redrawer.Direct3DRedrawer$frameDispatcher$1.invoke(Direct3DRedrawer.kt)
	at org.jetbrains.skiko.FrameDispatcher$job$1.invokeSuspend(FrameDispatcher.kt:33)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

### Platform Info

Aurora Version: 1.2-SNAPSHOT (1.2-20220513.221833-4)

**Comment by kirill-grouchnikov** [comment]
This is in either Compose itself or Skiko bindings. The last Aurora line in the stack [is here](https://github.com/kirill-grouchnikov/aurora/blob/icicle/theming/src/commonMain/kotlin/org/pushingpixels/aurora/theming/painter/fill/FractionBasedFillPainter.kt#L46) in `FractionBasedFillPainter`. That one [constructs](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui-graphics/src/commonMain/kotlin/androidx/compose/ui/graphics/Shader.kt;l=38) a `LinearGradientShader` with a list of `Color` objects. 

And you [can't create](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui-graphics/src/commonMain/kotlin/androidx/compose/ui/graphics/Color.kt;l=406) a `Color` with `alpha` greater than `1.0f`.

**Comment by kirill-grouchnikov** [comment]
I don't see what I can do in Aurora for this one, as I'm passing `Color` objects to the canvas APIs.

**Comment by kirill-grouchnikov** [comment]
I'll try to reproduce this in a standalone non-Aurora environment just to be sure.
